//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_REVISION = 1450;
        public const int COPYRIGHT_YEAR = 2013;
        
        public const int CHROME_VERSION_MAJOR = 31;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 1621;
        public const int CHROME_VERSION_PATCH = 0;
        
        public const string CEF_API_HASH_UNIVERSAL = "3e423846a27022b3d96950a1f6f783a1f226a94b";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "34d3c0c4ccb27ad5732e82b553844d9454e90c5e";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "16c5135a6dd7c0a37f1e4cbe3b5982290e7b50cc";
        public const string CEF_API_HASH_PLATFORM_LINUX = "e86349cade7079ca515627f26bdd8ca38d2aef0a";
    }
}
