//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_REVISION = 1435;
        public const int COPYRIGHT_YEAR = 2013;
        
        public const int CHROME_VERSION_MAJOR = 31;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 1621;
        public const int CHROME_VERSION_PATCH = 0;
        
        public const string CEF_API_HASH_UNIVERSAL = "72acb5fa6db631e7e09fc830a79a14650bd0b226";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "3798d1b50eebdb02cc0b55fd8bae59d6db06ae3f";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "8a596c38023c82c7153e4218c71545f371fb335a";
        public const string CEF_API_HASH_PLATFORM_LINUX = "ec60b7f2feccdf17d847532e8786874142b94302";
    }
}
